# Generated by Django 4.2.1 on 2023-05-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculadora", "0002_remove_ciclo_nome_remove_ciclo_valor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periodo",
            name="numero",
            field=models.IntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                ]
            ),
        ),
    ]
